[project]
name = "kokovilution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kokoro-onnx>=0.3.9",
    "librosa>=0.10.2.post1",
    "numpy>=2.1.3",
    "scipy>=1.15.1",
    "soundfile>=0.13.1",
]
